apiVersion: v1
data:
  config.yaml: |
    techPreviewUserWorkload:
      enabled: true
    prometheusUserWorkload:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      retention: 7d
      volumeClaimTemplate:
        metadata:
          name: prometheus
        spec:
          storageClassName: managed-premium
          resources:
            requests:
              storage: 50Gi
    alertmanagerMain:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      volumeClaimTemplate:
        spec:
          storageClassName: managed-premium
          resources:
            requests:
              storage: 50Gi
    prometheusK8s:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      volumeClaimTemplate:
        spec:
          storageClassName: managed-premium
          resources:
            requests:
              storage: 200Gi
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    grafana:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    k8sPrometheusAdapter:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    kubeStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    telemeterClient:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    openshiftStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
