apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "claim1" 
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi" 
  storageClassName: azure-file-storage
