apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: kube-bench
    job-name: kube-bench
  name: kube-bench-who-tfgvj-worker-northeurope1-4nh5z
  namespace: kubebench
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 200         
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec: 
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: kube-bench
        spec:
          containers:
          - command:
            - kube-bench
            image: aquasec/kube-bench:latest
            imagePullPolicy: Always
            name: kube-bench
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/lib/etcd
              name: var-lib-etcd
              readOnly: true
            - mountPath: /var/lib/kubelet
              name: var-lib-kubelet
              readOnly: true
            - mountPath: /etc/systemd
              name: etc-systemd
              readOnly: true
            - mountPath: /etc/kubernetes
              name: etc-kubernetes
              readOnly: true
            - mountPath: /usr/local/mount-from-host/bin
              name: usr-bin
              readOnly: true
          dnsPolicy: ClusterFirst
          hostPID: true
          serviceAccountName: kubebench
          restartPolicy: Never
          schedulerName: default-scheduler
          nodeSelector:
            kubernetes.io/hostname: who-tfgvj-worker-northeurope1-4nh5z
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - hostPath:
              path: /var/lib/etcd
              type: ""
            name: var-lib-etcd
          - hostPath:
              path: /var/lib/kubelet
              type: ""
            name: var-lib-kubelet
          - hostPath:
              path: /etc/systemd
              type: ""
            name: etc-systemd
          - hostPath:
              path: /etc/kubernetes
              type: ""
            name: etc-kubernetes
          - hostPath:
              path: /usr/bin
              type: ""
            name: usr-bin